/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 src/assets/glb/device.glb -o temp.jsx 
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/device.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="HiChord">
          <group name="Body" position={[0, 0.007, 0]} scale={[0.801, 1, 0.751]}>
            <mesh name="Cube" geometry={nodes.Cube.geometry} material={materials.BodyPlastic} />
            <mesh name="Cube_1" geometry={nodes.Cube_1.geometry} material={materials.Well} />
          </group>
          <group name="Body_Details" position={[-0.033, 0.002, -0.036]} scale={0}>
            <mesh name="Cube001" geometry={nodes.Cube001.geometry} material={materials.DisplayFrame} />
            <mesh name="Cube001_1" geometry={nodes.Cube001_1.geometry} material={materials.Display} />
            <mesh name="Cube001_2" geometry={nodes.Cube001_2.geometry} material={materials.ScreenText} />
          </group>
          <group name="Btn_GH" position={[0.011, -0.002, -0.036]} scale={0}>
            <mesh name="Btn_GH_1" geometry={nodes.Btn_GH_1.geometry} material={materials.GitHubDark} />
            <mesh name="Btn_GH_2" geometry={nodes.Btn_GH_2.geometry} material={materials.LegendWhite} />
          </group>
          <group name="Btn_LI" position={[-0.011, -0.002, -0.036]} scale={0}>
            <mesh name="Btn_LI_1" geometry={nodes.Btn_LI_1.geometry} material={materials.LinkedInBlue} />
            <mesh name="Btn_LI_2" geometry={nodes.Btn_LI_2.geometry} material={materials.LegendWhite} />
          </group>
          <group name="Btn_MD" position={[0.033, -0.002, -0.036]} scale={0}>
            <mesh name="Btn_MD_1" geometry={nodes.Btn_MD_1.geometry} material={materials.MediumBlack} />
            <mesh name="Btn_MD_2" geometry={nodes.Btn_MD_2.geometry} material={materials.LegendWhite} />
          </group>
          <group name="Key_Bot_0" position={[-0.033, 0.067, 0.022]} scale={0}>
            <mesh name="Key_Bot_0_1" geometry={nodes.Key_Bot_0_1.geometry} material={materials.Key} />
            <mesh name="Key_Bot_0_2" geometry={nodes.Key_Bot_0_2.geometry} material={materials.Dark} />
          </group>
          <group name="Key_Bot_1" position={[-0.011, 0.067, 0.022]} scale={0}>
            <mesh name="Key_Bot_1_1" geometry={nodes.Key_Bot_1_1.geometry} material={materials.Key} />
            <mesh name="Key_Bot_1_2" geometry={nodes.Key_Bot_1_2.geometry} material={materials.Dark} />
          </group>
          <group name="Key_Bot_2" position={[0.011, 0.067, 0.022]} scale={0}>
            <mesh name="Key_Bot_2_1" geometry={nodes.Key_Bot_2_1.geometry} material={materials.Key} />
            <mesh name="Key_Bot_2_2" geometry={nodes.Key_Bot_2_2.geometry} material={materials.Dark} />
          </group>
          <group name="Key_Bot_3" position={[0.033, 0.067, 0.022]} scale={0}>
            <mesh name="Key_Bot_3_1" geometry={nodes.Key_Bot_3_1.geometry} material={materials.ContactAmber} />
            <mesh name="Key_Bot_3_2" geometry={nodes.Key_Bot_3_2.geometry} material={materials.Dark} />
          </group>
          <group name="Key_Top_0" position={[-0.03, 0.067, -0.015]} scale={0}>
            <mesh name="Key_Top_0_1" geometry={nodes.Key_Top_0_1.geometry} material={materials.Key} />
            <mesh name="Key_Top_0_2" geometry={nodes.Key_Top_0_2.geometry} material={materials.Dark} />
          </group>
          <group name="Key_Top_1" position={[0, 0.067, -0.015]} scale={0}>
            <mesh name="Key_Top_1_1" geometry={nodes.Key_Top_1_1.geometry} material={materials.Key} />
            <mesh name="Key_Top_1_2" geometry={nodes.Key_Top_1_2.geometry} material={materials.Dark} />
          </group>
          <group name="Key_Top_2" position={[0.03, 0.067, -0.015]} scale={0}>
            <mesh name="Key_Top_2_1" geometry={nodes.Key_Top_2_1.geometry} material={materials.Key} />
            <mesh name="Key_Top_2_2" geometry={nodes.Key_Top_2_2.geometry} material={materials.Dark} />
          </group>
          <mesh name="Well_Fill" geometry={nodes.Well_Fill.geometry} material={materials.BodyPlastic} position={[0, 0.011, 0]} scale={[0.801, 1, 0.751]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/device.glb')
