/**
 * Build the photography wall's assets and manifest from src/assets/photography/.
 *
 *   npm run photos
 *
 * Adding a photo is then: drop it in src/assets/photography/, run this.
 *
 * Those originals are only ever read by this script — nothing imports them, so
 * Vite never bundles them. What ships is what this writes into public/photos/.
 *
 * Two sizes ship per photo. The wall draws a print about 300 mm wide on screen,
 * so a thumbnail carries it at any sane zoom, and thumbnails are what the wall
 * holds dozens of at once — they are the memory budget. The full size is loaded
 * only for the one print that has been clicked to fill the frame.
 *
 * `aspect` is measured here rather than read from the image at runtime, because
 * the layout is a masonry pack: column heights depend on every earlier photo's
 * aspect, so a runtime measure could not place anything until all the images had
 * partially loaded, and every late arrival would reflow the wall under the
 * pointer.
 *
 * sharp ships as a devDependency already, so this needs no extra install.
 */
import { mkdir, readdir, writeFile } from 'node:fs/promises'
import { basename, dirname, extname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const SRC_DIR = join(ROOT, 'src', 'assets', 'photography')
const FULL_DIR = join(ROOT, 'public', 'photos', 'full')
const THUMB_DIR = join(ROOT, 'public', 'photos', 'thumb')
const MANIFEST = join(ROOT, 'src', 'data', 'photos.generated.js')

const FULL_EDGE = 2000
const THUMB_EDGE = 800
const FULL_QUALITY = 82
const THUMB_QUALITY = 78
const SOURCE_EXT = new Set(['.jpg', '.jpeg', '.png', '.webp', '.tif', '.tiff', '.avif'])

async function load(name) {
  try {
    return (await import(name)).default
  } catch {
    console.error(`\nMissing "${name}". Install it with:\n\n  npm i -D ${name}\n`)
    process.exit(1)
  }
}

async function main() {
  const sharp = await load('sharp')

  await mkdir(FULL_DIR, { recursive: true })
  await mkdir(THUMB_DIR, { recursive: true })

  let files
  try {
    files = await readdir(SRC_DIR)
  } catch {
    console.error(`\nNo src/assets/photography/ directory. Create it and drop photos in.\n`)
    process.exit(1)
  }

  /*
   * Sorted so the manifest — and therefore the wall's masonry packing — is the
   * same on every machine and in every checkout.
   *
   * Numeric-aware, so img2 comes before img10 rather than after it. Plain
   * lexical order would hang the wall in an order that does not match how the
   * files read in a directory listing, which makes it needlessly hard to work
   * out which photo is which when adjusting captions.
   */
  const sources = files
    .filter((f) => SOURCE_EXT.has(extname(f).toLowerCase()))
    .sort((a, b) => a.localeCompare(b, undefined, { numeric: true }))

  if (sources.length === 0) {
    console.error(`\nsrc/assets/photography/ has no images. Supported: ${[...SOURCE_EXT].join(', ')}\n`)
    process.exit(1)
  }

  const manifest = []
  for (const file of sources) {
    const id = basename(file, extname(file))
    const img = sharp(join(SRC_DIR, file), { failOn: 'error' })
    const meta = await img.metadata()

    // EXIF orientation is applied by `rotate()` on output, but metadata still
    // reports the stored dimensions, so a portrait shot saved as landscape plus
    // a rotation flag would otherwise be laid out on its side.
    const upright = meta.orientation >= 5 && meta.orientation <= 8
    const width = upright ? meta.height : meta.width
    const height = upright ? meta.width : meta.height

    await img.clone().rotate().resize(FULL_EDGE, FULL_EDGE, { fit: 'inside', withoutEnlargement: true })
      .webp({ quality: FULL_QUALITY }).toFile(join(FULL_DIR, `${id}.webp`))
    await img.clone().rotate().resize(THUMB_EDGE, THUMB_EDGE, { fit: 'inside', withoutEnlargement: true })
      .webp({ quality: THUMB_QUALITY }).toFile(join(THUMB_DIR, `${id}.webp`))

    manifest.push({
      id,
      src: `/photos/full/${id}.webp`,
      thumb: `/photos/thumb/${id}.webp`,
      aspect: Number((width / height).toFixed(4)),
    })
    console.log(`  ${id}  ${width}×${height}  aspect ${(width / height).toFixed(2)}`)
  }

  await writeFile(
    MANIFEST,
    `/**\n * Generated by scripts/prepare-photos.mjs — do not edit.\n *\n` +
      ` * Captions, locations and years live in src/data/photos.js, keyed by id, so\n` +
      ` * that re-running the script never overwrites anything written by hand.\n */\n` +
      `export const GENERATED_PHOTOS = ${JSON.stringify(manifest, null, 2)}\n`
  )

  console.log(`\n${manifest.length} photos → public/photos/, manifest → src/data/photos.generated.js\n`)
}

main()
